name: Run NFPC monitor daily 9am KST

on:
  schedule:
    # GitHub Actions는 UTC 기준. KST 09:00 = UTC 00:00
    - cron: "0 0 * * *"
  workflow_dispatch: {}  # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run NFPC script
        env:
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          python NFPC.py
